import { useState } from 'react';
import { ShoppingBag, Trash2 } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { useCartStore } from '../../stores/useCartStore';
import { useUIStore } from '../../stores/useUIStore';
import { formatCurrency } from '../../utils/format';
import { Button, ConfirmDialog, EmptyState, QuantitySelector } from '../common/ui';

export const CartPanel = ({ compact = false, onCheckout }: { compact?: boolean; onCheckout?: () => void }) => {
  const { items, subtotal, shippingFee, discount, total, totalQuantity, updateQuantity, removeItem, clearCart } = useCartStore();
  const showToast = useUIStore((state) => state.showToast); const [removeId, setRemoveId] = useState<string | null>(null); const [confirmClear, setConfirmClear] = useState(false); const navigate = useNavigate();
  if (items.length === 0) return <EmptyState icon={<ShoppingBag size={34}/>} title="購物車還是空的" description="從今日菜單挑選喜歡的餐點吧。" action={<Button onClick={() => navigate('/menu')}>瀏覽菜單</Button>}/>;
  return <div className="flex h-full flex-col"><div className="mb-4 flex items-center justify-between"><div><h2 className="font-semibold text-stone-900">購物車 <span className="text-[#9a6b2f]">({totalQuantity})</span></h2><p className="mt-0.5 text-xs text-stone-400">重新整理後仍會保留</p></div><Button variant="ghost" size="sm" onClick={() => setConfirmClear(true)}>清空</Button></div><div className={compact ? 'max-h-[48vh] flex-1 space-y-3 overflow-y-auto pr-1' : 'flex-1 space-y-3 overflow-y-auto pr-1'}>{items.map((item) => <article key={item.id} className="rounded-xl border border-stone-100 bg-stone-50/60 p-3"><div className="flex gap-3"><img src={item.meal.image} alt={item.meal.name} className="h-16 w-16 rounded-lg object-cover"/><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-2"><div><h3 className="truncate text-sm font-medium">{item.meal.name}</h3><p className="mt-0.5 text-xs text-stone-400">{item.meal.options.filter((option) => item.optionIds.includes(option.id)).map((option) => option.name).join('、') || '標準餐點'}</p>{item.note && <p className="mt-0.5 truncate text-xs text-stone-400">備註：{item.note}</p>}</div><button aria-label={`刪除${item.meal.name}`} onClick={() => setRemoveId(item.id)} className="rounded-md p-1 text-stone-400 hover:bg-red-50 hover:text-[#9a514a]"><Trash2 size={15}/></button></div><div className="mt-2 flex items-center justify-between"><QuantitySelector size="sm" value={item.quantity} max={item.meal.stock} onChange={(quantity) => updateQuantity(item.id, quantity)}/><span className="text-sm font-semibold">{formatCurrency(item.unitPrice * item.quantity)}</span></div></div></div></article>)}</div><div className="mt-4 space-y-2 border-t border-stone-100 pt-4 text-sm"><div className="flex justify-between text-stone-500"><span>商品小計</span><span>{formatCurrency(subtotal)}</span></div><div className="flex justify-between text-stone-500"><span>運費</span><span>{shippingFee === 0 ? '免運' : formatCurrency(shippingFee)}</span></div>{discount > 0 && <div className="flex justify-between text-[#5f725d]"><span>滿額折扣</span><span>−{formatCurrency(discount)}</span></div>}<div className="flex items-end justify-between border-t border-stone-100 pt-3"><span className="font-medium">總計</span><strong className="text-xl text-[#6d5125]">{formatCurrency(total)}</strong></div><Button className="mt-2 w-full" onClick={() => { onCheckout?.(); navigate('/checkout'); }}>前往結帳</Button></div><ConfirmDialog open={removeId !== null} onClose={() => setRemoveId(null)} onConfirm={() => { if (removeId) removeItem(removeId); showToast('已從購物車移除餐點'); }} title="移除餐點？" description="確定要將這項餐點移出購物車嗎？" confirmLabel="移除"/><ConfirmDialog open={confirmClear} onClose={() => setConfirmClear(false)} onConfirm={() => { clearCart(); showToast('購物車已清空'); }} title="清空購物車？" description="購物車內的所有餐點與客製選項都會移除。" confirmLabel="全部清空"/></div>;
};

export const GlobalCartDrawer = () => {
  const open = useUIStore((state) => state.isCartOpen); const close = useUIStore((state) => state.closeCart);
  return <div className={`fixed inset-0 z-50 ${open ? 'pointer-events-auto' : 'pointer-events-none'}`} aria-hidden={!open}><div className={`absolute inset-0 bg-stone-950/30 transition-opacity ${open ? 'opacity-100' : 'opacity-0'}`} onClick={close}/><aside className={`absolute inset-y-0 right-0 w-[min(94vw,430px)] bg-white p-5 shadow-2xl transition-transform ${open ? 'translate-x-0' : 'translate-x-full'}`}><button onClick={close} aria-label="關閉購物車" className="absolute right-4 top-4 z-10 rounded-lg px-2 py-1 text-xl text-stone-400 hover:bg-stone-100">×</button><CartPanel onCheckout={close}/></aside></div>;
};
