import { useState } from 'react';
import { zodResolver } from '@hookform/resolvers/zod';
import { Eye, EyeOff, LockKeyhole, Soup, UserRound } from 'lucide-react';
import { useForm } from 'react-hook-form';
import { Link, Navigate, useNavigate } from 'react-router-dom';
import { loginSchema, type LoginForm } from '../../schemas';
import { useAuthStore } from '../../stores/useAuthStore';
import { Button, Checkbox, FormField, Input } from '../../components/common/ui';

export const LoginPage = () => {
  const [showPassword, setShowPassword] = useState(false); const login = useAuthStore((state) => state.login); const isAuthenticated = useAuthStore((state) => state.isAuthenticated); const navigate = useNavigate();
  const { register, handleSubmit, setError, formState: { errors, isSubmitting } } = useForm<LoginForm>({ resolver: zodResolver(loginSchema), defaultValues: { account: 'admin@mealflow.tw', password: '123456', remember: true } });
  if (isAuthenticated) return <Navigate to="/" replace/>;
  const onSubmit = async (values: LoginForm) => { const success = await login(values.account, values.password); if (!success) { setError('account', { message: '帳號或密碼錯誤，請重新輸入' }, { shouldFocus: true }); return; } navigate('/'); };
  return <main className="grid min-h-screen bg-[#efede7] lg:grid-cols-[1.1fr_.9fr]"><section className="relative hidden overflow-hidden lg:block"><img src="/meals/hero.svg" alt="豐盛健康的便當餐桌插畫" className="absolute inset-0 h-full w-full object-cover"/><div className="absolute inset-0 bg-gradient-to-t from-stone-950/55 via-stone-950/15 to-transparent"/><div className="absolute bottom-12 left-12 max-w-xl text-white"><p className="text-sm font-medium tracking-[.2em] text-white/75">讓午餐成為團隊的一件小事</p><h1 className="mt-4 text-4xl font-semibold leading-tight">把每一份期待，<br/>準時送到工作日常。</h1><p className="mt-4 max-w-md text-sm leading-7 text-white/75">企業訂餐、團體管理與數據報表，一個平台就能自在完成。</p></div></section><section className="flex items-center justify-center p-5 sm:p-10"><div className="w-full max-w-md rounded-[18px] border border-white/80 bg-white p-6 shadow-[0_24px_70px_rgba(58,48,31,.12)] sm:p-9"><div className="mb-8 text-center"><div className="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-[#403a2c] text-white"><Soup size={27}/></div><h2 className="mt-4 text-2xl font-semibold tracking-wide text-stone-900">食刻便當</h2><p className="mt-1 text-xs uppercase tracking-[.22em] text-stone-400">MealFlow · 企業訂餐系統</p></div><form onSubmit={handleSubmit(onSubmit)} className="space-y-4" noValidate><FormField label="帳號" error={errors.account?.message} required><div className="relative"><UserRound className="absolute left-3 top-1/2 -translate-y-1/2 text-stone-400" size={17}/><Input autoComplete="username" className="pl-10" placeholder="請輸入公司帳號" {...register('account')}/></div></FormField><FormField label="密碼" error={errors.password?.message} required><div className="relative"><LockKeyhole className="absolute left-3 top-1/2 -translate-y-1/2 text-stone-400" size={17}/><Input autoComplete="current-password" type={showPassword ? 'text' : 'password'} className="pl-10 pr-11" placeholder="請輸入密碼" {...register('password')}/><button type="button" onClick={() => setShowPassword((value) => !value)} aria-label={showPassword ? '隱藏密碼' : '顯示密碼'} className="absolute right-1.5 top-1/2 grid h-9 w-9 -translate-y-1/2 place-items-center rounded-lg text-stone-400 hover:bg-stone-100">{showPassword ? <EyeOff size={17}/> : <Eye size={17}/>}</button></div></FormField><div className="flex items-center justify-between"><Checkbox label="記住我" {...register('remember')}/><button type="button" className="text-xs text-[#75694f] hover:underline">忘記密碼？</button></div><Button type="submit" className="w-full" disabled={isSubmitting}>{isSubmitting ? '登入中…' : '登入'}</Button></form><p className="mt-6 text-center text-xs text-stone-400">還沒有帳號？ <Link to="/login" className="font-medium text-[#75694f] hover:underline">立即註冊</Link></p><div className="mt-7 rounded-xl bg-[#f7f5f0] p-3 text-center text-[11px] leading-5 text-stone-500">展示帳號已預填，直接登入即可。<br/>帳號包含 member 時會以一般員工權限登入。</div></div></section></main>;
};
