import { useState } from 'react';
import { zodResolver } from '@hookform/resolvers/zod';
import { Bell, Camera, KeyRound, UserRound } from 'lucide-react';
import { useForm } from 'react-hook-form';
import { Button, Card, FormField, Input, PageHeader, Switch } from '../../components/common/ui';
import { passwordSchema, profileSchema, type PasswordForm, type ProfileForm } from '../../schemas';
import { useAuthStore } from '../../stores/useAuthStore';
import { useUIStore } from '../../stores/useUIStore';

type SettingsTab = 'profile' | 'password' | 'notifications';
export const SettingsPage = () => { const [tab, setTab] = useState<SettingsTab>('profile'); const items: Array<{ id: SettingsTab; label: string; icon: typeof UserRound }> = [{ id: 'profile', label: '個人資料', icon: UserRound }, { id: 'password', label: '修改密碼', icon: KeyRound }, { id: 'notifications', label: '通知設定', icon: Bell }]; return <div className="space-y-5"><PageHeader eyebrow="ACCOUNT" title="帳號設定" description="管理個人資料、安全性與接收通知的方式。"/><div className="grid items-start gap-5 lg:grid-cols-[220px_1fr]"><Card className="p-2">{items.map(({ id, label, icon: Icon }) => <button key={id} onClick={() => setTab(id)} className={`flex min-h-11 w-full items-center gap-3 rounded-[10px] px-3 text-sm ${tab === id ? 'bg-[#f2eee5] font-medium text-[#403a2c]' : 'text-stone-500 hover:bg-stone-50'}`}><Icon size={18}/>{label}</button>)}</Card>{tab === 'profile' ? <ProfilePanel/> : tab === 'password' ? <PasswordPanel/> : <NotificationsPanel/>}</div></div>; };

const ProfilePanel = () => { const user = useAuthStore((state) => state.user); const updateProfile = useAuthStore((state) => state.updateProfile); const showToast = useUIStore((state) => state.showToast); const { register, handleSubmit, formState: { errors, isSubmitting } } = useForm<ProfileForm>({ resolver: zodResolver(profileSchema), defaultValues: { name: user?.name ?? '', email: user?.email ?? '', phone: user?.phone ?? '' } }); const onSubmit = async (values: ProfileForm) => { await new Promise<void>((resolve) => window.setTimeout(resolve, 450)); updateProfile(values); showToast('個人資料已更新'); }; return <Card className="p-5 sm:p-7"><h2 className="font-semibold">個人資料</h2><div className="mt-6 flex items-center gap-4 border-b border-stone-100 pb-6"><div className="relative grid h-20 w-20 place-items-center rounded-full bg-[#e9e3d7] text-2xl font-semibold text-[#675c45]">{user?.name.slice(0, 1)}<button aria-label="更換頭像" className="absolute -bottom-1 -right-1 grid h-8 w-8 place-items-center rounded-full border-2 border-white bg-[#403a2c] text-white"><Camera size={14}/></button></div><div><p className="font-medium">{user?.name}</p><p className="mt-1 text-sm text-stone-400">{user?.departmentName} · {user?.title}</p></div></div><form onSubmit={handleSubmit(onSubmit)} className="mt-6 grid max-w-2xl gap-4 sm:grid-cols-2"><FormField label="姓名" error={errors.name?.message} required><Input {...register('name')}/></FormField><FormField label="Email" error={errors.email?.message} required><Input type="email" {...register('email')}/></FormField><FormField label="手機" error={errors.phone?.message} required><Input {...register('phone')}/></FormField><FormField label="部門"><Input value={user?.departmentName ?? ''} disabled/></FormField><div className="sm:col-span-2"><Button type="submit" disabled={isSubmitting}>{isSubmitting ? '儲存中…' : '儲存變更'}</Button></div></form></Card>; };

const PasswordPanel = () => { const showToast = useUIStore((state) => state.showToast); const { register, handleSubmit, reset, formState: { errors, isSubmitting } } = useForm<PasswordForm>({ resolver: zodResolver(passwordSchema), defaultValues: { currentPassword: '', newPassword: '', confirmPassword: '' } }); const onSubmit = async () => { await new Promise<void>((resolve) => window.setTimeout(resolve, 500)); reset(); showToast('密碼已更新'); }; return <Card className="p-5 sm:p-7"><h2 className="font-semibold">修改密碼</h2><p className="mt-1 text-sm text-stone-400">為確保帳號安全，請使用至少 8 個字元的新密碼。</p><form onSubmit={handleSubmit(onSubmit)} className="mt-6 max-w-lg space-y-4"><FormField label="目前密碼" error={errors.currentPassword?.message} required><Input type="password" autoComplete="current-password" {...register('currentPassword')}/></FormField><FormField label="新密碼" error={errors.newPassword?.message} required><Input type="password" autoComplete="new-password" {...register('newPassword')}/></FormField><FormField label="確認新密碼" error={errors.confirmPassword?.message} required><Input type="password" autoComplete="new-password" {...register('confirmPassword')}/></FormField><Button type="submit" disabled={isSubmitting}>{isSubmitting ? '更新中…' : '更新密碼'}</Button></form></Card>; };

const NotificationsPanel = () => { const [orderStatus, setOrderStatus] = useState(true); const [deadline, setDeadline] = useState(true); const [email, setEmail] = useState(false); const [system, setSystem] = useState(true); const showToast = useUIStore((state) => state.showToast); return <Card className="p-5 sm:p-7"><h2 className="font-semibold">通知設定</h2><p className="mt-1 text-sm text-stone-400">選擇想收到的提醒，重要的訂單異動不會錯過。</p><div className="mt-6 max-w-2xl divide-y divide-stone-100 rounded-xl border border-stone-100 px-4"><Switch checked={orderStatus} onChange={setOrderStatus} label="訂單狀態通知"/><Switch checked={deadline} onChange={setDeadline} label="訂餐截止提醒"/><Switch checked={email} onChange={setEmail} label="Email 通知"/><Switch checked={system} onChange={setSystem} label="系統通知"/></div><Button className="mt-5" onClick={() => showToast('通知設定已儲存')}>儲存設定</Button></Card>; };
