import { forwardRef, useEffect, useId, type ButtonHTMLAttributes, type InputHTMLAttributes, type ReactNode, type SelectHTMLAttributes, type TextareaHTMLAttributes } from 'react';
import { AlertCircle, CheckCircle2, ChevronLeft, ChevronRight, Search, X } from 'lucide-react';
import { cn } from '../../utils/cn';
import { useUIStore } from '../../stores/useUIStore';

export const Button = ({ className, variant = 'primary', size = 'md', type = 'button', ...props }: ButtonHTMLAttributes<HTMLButtonElement> & { variant?: 'primary' | 'secondary' | 'ghost' | 'danger'; size?: 'sm' | 'md' | 'icon' }) => (
  <button type={type} className={cn('inline-flex min-h-10 items-center justify-center gap-2 rounded-[10px] font-medium transition focus:outline-none focus:ring-2 focus:ring-[#6f6248] focus:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-45',
    variant === 'primary' && 'bg-[#403a2c] text-white hover:bg-[#29261e] active:scale-[.98]', variant === 'secondary' && 'border border-stone-200 bg-white text-stone-700 hover:border-stone-300 hover:bg-stone-50',
    variant === 'ghost' && 'text-stone-600 hover:bg-stone-100 hover:text-stone-900', variant === 'danger' && 'bg-[#9a5750] text-white hover:bg-[#7f4640]', size === 'sm' && 'min-h-9 px-3 text-xs', size === 'md' && 'px-4 text-sm', size === 'icon' && 'h-10 w-10 p-0', className)} {...props} />
);

export const Input = forwardRef<HTMLInputElement, InputHTMLAttributes<HTMLInputElement>>(({ className, ...props }, ref) => <input ref={ref} className={cn('h-11 w-full rounded-[10px] border border-stone-200 bg-white px-3 text-sm text-stone-800 outline-none transition placeholder:text-stone-400 focus:border-[#75694f] focus:ring-2 focus:ring-[#75694f]/15 disabled:bg-stone-100', className)} {...props} />);
Input.displayName = 'Input';
export const Select = forwardRef<HTMLSelectElement, SelectHTMLAttributes<HTMLSelectElement>>(({ className, children, ...props }, ref) => <select ref={ref} className={cn('h-11 w-full rounded-[10px] border border-stone-200 bg-white px-3 text-sm text-stone-700 outline-none transition focus:border-[#75694f] focus:ring-2 focus:ring-[#75694f]/15', className)} {...props}>{children}</select>);
Select.displayName = 'Select';
export const Textarea = forwardRef<HTMLTextAreaElement, TextareaHTMLAttributes<HTMLTextAreaElement>>(({ className, ...props }, ref) => <textarea ref={ref} className={cn('min-h-24 w-full resize-y rounded-[10px] border border-stone-200 bg-white px-3 py-2.5 text-sm outline-none transition focus:border-[#75694f] focus:ring-2 focus:ring-[#75694f]/15', className)} {...props} />);
Textarea.displayName = 'Textarea';

export const Checkbox = forwardRef<HTMLInputElement, InputHTMLAttributes<HTMLInputElement> & { label: string }>(({ label, ...props }, ref) => <label className="inline-flex min-h-10 cursor-pointer items-center gap-2 text-sm text-stone-600"><input ref={ref} type="checkbox" className="h-4 w-4 rounded border-stone-300 accent-[#403a2c] focus:ring-[#75694f]" {...props} /><span>{label}</span></label>);
Checkbox.displayName = 'Checkbox';

export const RadioGroup = ({ label, name, options, value, onChange }: { label: string; name: string; options: Array<{ value: string; label: string; description?: string }>; value: string; onChange: (value: string) => void }) => (
  <fieldset><legend className="mb-2 text-sm font-medium text-stone-700">{label}</legend><div className="grid gap-2 sm:grid-cols-2">{options.map((option) => <label key={option.value} className={cn('flex cursor-pointer gap-3 rounded-[10px] border p-3 transition', value === option.value ? 'border-[#75694f] bg-[#f4f0e7]' : 'border-stone-200 hover:bg-stone-50')}><input type="radio" name={name} value={option.value} checked={value === option.value} onChange={() => onChange(option.value)} className="mt-1 accent-[#403a2c]"/><span><span className="block text-sm font-medium">{option.label}</span>{option.description && <span className="text-xs text-stone-500">{option.description}</span>}</span></label>)}</div></fieldset>
);

export const Switch = ({ checked, onChange, label }: { checked: boolean; onChange: (value: boolean) => void; label: string }) => <label className="flex cursor-pointer items-center justify-between gap-4 py-2"><span className="text-sm text-stone-700">{label}</span><button type="button" role="switch" aria-checked={checked} onClick={() => onChange(!checked)} className={cn('relative h-6 w-11 rounded-full transition focus:outline-none focus:ring-2 focus:ring-[#75694f] focus:ring-offset-2', checked ? 'bg-[#5f725d]' : 'bg-stone-300')}><span className={cn('absolute top-0.5 h-5 w-5 rounded-full bg-white shadow transition', checked ? 'left-[22px]' : 'left-0.5')} /></button></label>;

export const Badge = ({ children, tone = 'neutral', className }: { children: ReactNode; tone?: 'neutral' | 'success' | 'warning' | 'danger'; className?: string }) => <span className={cn('inline-flex items-center rounded-full px-2.5 py-1 text-xs font-medium', tone === 'neutral' && 'bg-stone-100 text-stone-600', tone === 'success' && 'bg-[#edf4ea] text-[#52704f]', tone === 'warning' && 'bg-[#fbf1df] text-[#9a6b2f]', tone === 'danger' && 'bg-[#f9e9e7] text-[#9a514a]', className)}>{children}</span>;
export const Card = ({ children, className }: { children: ReactNode; className?: string }) => <section className={cn('rounded-[14px] border border-stone-200/80 bg-white shadow-[0_4px_18px_rgba(62,53,38,.035)]', className)}>{children}</section>;

export const FormField = ({ label, error, hint, required, children }: { label: string; error?: string; hint?: string; required?: boolean; children: ReactNode }) => <label className="block"><span className="mb-1.5 block text-sm font-medium text-stone-700">{label}{required && <span className="ml-1 text-[#9a514a]">*</span>}</span>{children}{error ? <span className="mt-1 flex items-center gap-1 text-xs text-[#9a514a]"><AlertCircle size={13}/>{error}</span> : hint ? <span className="mt-1 block text-xs text-stone-400">{hint}</span> : null}</label>;

export const Modal = ({ open, onClose, title, children, footer, size = 'md' }: { open: boolean; onClose: () => void; title: string; children: ReactNode; footer?: ReactNode; size?: 'sm' | 'md' | 'lg' }) => {
  useEffect(() => { if (!open) return; const onKeyDown = (event: KeyboardEvent) => { if (event.key === 'Escape') onClose(); }; document.addEventListener('keydown', onKeyDown); document.body.style.overflow = 'hidden'; return () => { document.removeEventListener('keydown', onKeyDown); document.body.style.overflow = ''; }; }, [open, onClose]);
  if (!open) return null;
  return <div className="fixed inset-0 z-50 flex items-end justify-center bg-stone-950/35 backdrop-blur-[2px] sm:items-center sm:p-4" onMouseDown={(event) => { if (event.currentTarget === event.target) onClose(); }}><div role="dialog" aria-modal="true" aria-label={title} className={cn('flex max-h-[92vh] w-full flex-col overflow-hidden bg-white shadow-2xl sm:rounded-[14px]', size === 'sm' && 'sm:max-w-md', size === 'md' && 'sm:max-w-2xl', size === 'lg' && 'sm:max-w-4xl')}><div className="flex items-center justify-between border-b border-stone-100 px-5 py-4"><h2 className="text-lg font-semibold text-stone-900">{title}</h2><Button variant="ghost" size="icon" aria-label="關閉" onClick={onClose}><X size={19}/></Button></div><div className="overflow-y-auto p-5">{children}</div>{footer && <div className="border-t border-stone-100 bg-stone-50/60 px-5 py-4">{footer}</div>}</div></div>;
};

export const ConfirmDialog = ({ open, onClose, onConfirm, title, description, confirmLabel = '確認' }: { open: boolean; onClose: () => void; onConfirm: () => void; title: string; description: string; confirmLabel?: string }) => <Modal open={open} onClose={onClose} title={title} size="sm"><p className="text-sm leading-6 text-stone-600">{description}</p><div className="mt-6 flex justify-end gap-2"><Button variant="secondary" onClick={onClose}>取消</Button><Button variant="danger" onClick={() => { onConfirm(); onClose(); }}>{confirmLabel}</Button></div></Modal>;
export const Drawer = ({ open, onClose, title, children }: { open: boolean; onClose: () => void; title: string; children: ReactNode }) => <div className={cn('fixed inset-0 z-50 transition', open ? 'pointer-events-auto' : 'pointer-events-none')} aria-hidden={!open}><div className={cn('absolute inset-0 bg-stone-950/30 transition-opacity', open ? 'opacity-100' : 'opacity-0')} onClick={onClose}/><aside className={cn('absolute inset-y-0 right-0 flex w-[min(92vw,420px)] flex-col bg-white shadow-2xl transition-transform', open ? 'translate-x-0' : 'translate-x-full')}><div className="flex items-center justify-between border-b px-5 py-4"><h2 className="font-semibold">{title}</h2><Button variant="ghost" size="icon" onClick={onClose} aria-label="關閉"><X size={19}/></Button></div><div className="flex-1 overflow-y-auto p-5">{children}</div></aside></div>;
export const BottomSheet = ({ open, onClose, title, children }: { open: boolean; onClose: () => void; title: string; children: ReactNode }) => <Modal open={open} onClose={onClose} title={title}>{children}</Modal>;

export const Toast = () => {
  const toast = useUIStore((state) => state.toast); const hideToast = useUIStore((state) => state.hideToast);
  useEffect(() => { if (!toast) return; const timer = window.setTimeout(hideToast, 2800); return () => window.clearTimeout(timer); }, [toast, hideToast]);
  if (!toast) return null;
  return <div role="status" className={cn('fixed bottom-20 left-1/2 z-[70] flex min-w-72 -translate-x-1/2 items-center gap-3 rounded-xl border bg-white px-4 py-3 text-sm shadow-xl md:bottom-6 md:left-auto md:right-6 md:translate-x-0', toast.type === 'error' ? 'border-red-200' : 'border-stone-200')}>{toast.type === 'success' ? <CheckCircle2 className="text-[#5f725d]" size={19}/> : <AlertCircle className={toast.type === 'error' ? 'text-[#9a514a]' : 'text-[#a57635]'} size={19}/>}<span className="flex-1">{toast.message}</span><button onClick={hideToast} aria-label="關閉通知"><X size={16}/></button></div>;
};

export const Skeleton = ({ className }: { className?: string }) => <div className={cn('animate-pulse rounded-lg bg-stone-200/70', className)} />;
export const EmptyState = ({ icon, title, description, action }: { icon?: ReactNode; title: string; description: string; action?: ReactNode }) => <div className="flex min-h-56 flex-col items-center justify-center px-6 py-10 text-center"><div className="mb-3 text-stone-400">{icon}</div><h3 className="font-semibold text-stone-800">{title}</h3><p className="mt-1 max-w-sm text-sm leading-6 text-stone-500">{description}</p>{action && <div className="mt-4">{action}</div>}</div>;

export const SearchInput = ({ value, onChange, placeholder = '搜尋…' }: { value: string; onChange: (value: string) => void; placeholder?: string }) => <div className="relative"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-stone-400" size={17}/><Input value={value} onChange={(event) => onChange(event.target.value)} placeholder={placeholder} className="pl-9 pr-9"/>{value && <button type="button" onClick={() => onChange('')} aria-label="清除搜尋" className="absolute right-2 top-1/2 flex h-8 w-8 -translate-y-1/2 items-center justify-center rounded-md text-stone-400 hover:bg-stone-100"><X size={15}/></button>}</div>;
export const Pagination = ({ page, totalPages, onChange }: { page: number; totalPages: number; onChange: (page: number) => void }) => <nav aria-label="分頁" className="flex items-center justify-center gap-1"><Button variant="secondary" size="icon" disabled={page <= 1} onClick={() => onChange(page - 1)} aria-label="上一頁"><ChevronLeft size={16}/></Button>{Array.from({ length: totalPages }, (_, index) => index + 1).map((number) => <Button key={number} variant={number === page ? 'primary' : 'secondary'} size="icon" onClick={() => onChange(number)}>{number}</Button>)}<Button variant="secondary" size="icon" disabled={page >= totalPages} onClick={() => onChange(page + 1)} aria-label="下一頁"><ChevronRight size={16}/></Button></nav>;

export interface DataColumn<T> { key: string; title: string; render: (item: T) => ReactNode; className?: string; }
export const DataTable = <T,>({ data, columns, getKey }: { data: T[]; columns: Array<DataColumn<T>>; getKey: (item: T) => string }) => <div className="overflow-x-auto"><table className="w-full min-w-[680px] text-left text-sm"><thead className="border-b border-stone-200 bg-stone-50 text-xs uppercase tracking-wide text-stone-500"><tr>{columns.map((column) => <th key={column.key} className={cn('px-4 py-3 font-medium', column.className)}>{column.title}</th>)}</tr></thead><tbody className="divide-y divide-stone-100">{data.map((item) => <tr key={getKey(item)} className="hover:bg-stone-50/70">{columns.map((column) => <td key={column.key} className={cn('px-4 py-3.5', column.className)}>{column.render(item)}</td>)}</tr>)}</tbody></table></div>;

export const DateRangePicker = ({ start, end, onStartChange, onEndChange }: { start: string; end: string; onStartChange: (value: string) => void; onEndChange: (value: string) => void }) => <div className="flex items-center gap-2"><Input aria-label="開始日期" type="date" value={start} onChange={(event) => onStartChange(event.target.value)}/><span className="text-stone-400">–</span><Input aria-label="結束日期" type="date" value={end} onChange={(event) => onEndChange(event.target.value)}/></div>;
export const PageHeader = ({ eyebrow, title, description, actions }: { eyebrow?: string; title: string; description?: string; actions?: ReactNode }) => <div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div>{eyebrow && <p className="mb-1 text-xs font-semibold uppercase tracking-[.18em] text-[#8a7a58]">{eyebrow}</p>}<h1 className="text-2xl font-semibold tracking-tight text-stone-900 sm:text-[28px]">{title}</h1>{description && <p className="mt-1 text-sm text-stone-500">{description}</p>}</div>{actions && <div className="flex flex-wrap gap-2">{actions}</div>}</div>;
export const StatCard = ({ label, value, trend, icon }: { label: string; value: string; trend?: number; icon?: ReactNode }) => <Card className="p-4 sm:p-5"><div className="flex items-start justify-between"><p className="text-sm text-stone-500">{label}</p>{icon && <div className="rounded-lg bg-[#f4f0e7] p-2 text-[#675c45]">{icon}</div>}</div><p className="mt-2 text-2xl font-semibold text-stone-900">{value}</p>{trend !== undefined && <p className={cn('mt-2 text-xs', trend >= 0 ? 'text-[#5f725d]' : 'text-[#a4564f]')}>{trend >= 0 ? '↑' : '↓'} {Math.abs(trend)}% 較上期</p>}</Card>;

export const QuantitySelector = ({ value, onChange, max = 99, size = 'md' }: { value: number; onChange: (value: number) => void; max?: number; size?: 'sm' | 'md' }) => { const id = useId(); return <div className={cn('inline-flex items-center rounded-lg border border-stone-200 bg-white', size === 'sm' ? 'h-8' : 'h-10')}><button type="button" aria-label="減少數量" disabled={value <= 1} onClick={() => onChange(value - 1)} className="h-full px-3 text-stone-600 disabled:opacity-30">−</button><output htmlFor={id} id={id} className="min-w-5 text-center text-sm">{value}</output><button type="button" aria-label="增加數量" disabled={value >= max} onClick={() => onChange(value + 1)} className="h-full px-3 text-stone-600 disabled:opacity-30">＋</button></div>; };
