import { ArrowLeft, Check, Clock3, MapPin, ReceiptText, UserRound } from 'lucide-react';
import { useNavigate, useParams } from 'react-router-dom';
import { Button, Card, EmptyState, PageHeader } from '../../components/common/ui';
import { OrderStatusBadge, OrderSummary } from '../../components/orders/OrderComponents';
import { useOrderStore } from '../../stores/useOrderStore';
import { formatDate, invoiceLabels, paymentLabels } from '../../utils/format';

export const OrderDetailPage = () => { const { orderId } = useParams(); const orders = useOrderStore((state) => state.orders); const navigate = useNavigate(); const order = orders.find((entry) => entry.id === orderId); if (!order) return <Card><EmptyState title="找不到這筆訂單" description="訂單可能已被移除，請返回訂單列表查看。" action={<Button onClick={() => navigate('/orders')}>返回我的訂單</Button>}/></Card>; return <div className="space-y-5"><PageHeader title="訂單詳情" description={`#${order.id}`} actions={<Button variant="secondary" onClick={() => navigate('/orders')}><ArrowLeft size={16}/>返回列表</Button>}/><div className="grid items-start gap-5 xl:grid-cols-[minmax(0,1fr)_360px]"><div className="space-y-5"><Card className="p-5 sm:p-6"><div className="flex items-center justify-between"><div><p className="text-xs text-stone-400">訂單狀態</p><div className="mt-2"><OrderStatusBadge status={order.status}/></div></div><p className="text-xs text-stone-400">建立於 {formatDate(order.orderedAt)}</p></div><dl className="mt-6 grid gap-5 border-t border-stone-100 pt-5 sm:grid-cols-2"><Info icon={<UserRound/>} label="訂購人資訊" value={`${order.customerName} · ${order.customerPhone}\n${order.department}`}/><Info icon={<Clock3/>} label="送餐日期與時段" value={`${formatDate(order.deliveryDate)}\n${order.deliveryTime}`}/><Info icon={<MapPin/>} label="送餐地點" value={order.deliveryLocation}/><Info icon={<ReceiptText/>} label="付款與發票" value={`${paymentLabels[order.paymentMethod]} · ${invoiceLabels[order.invoiceType]}${order.invoiceTitle ? `\n${order.invoiceTitle} ${order.taxId ?? ''}` : ''}`}/></dl>{order.note && <div className="mt-5 rounded-xl bg-stone-50 p-4"><p className="text-xs text-stone-400">訂單備註</p><p className="mt-1 text-sm">{order.note}</p></div>}</Card><Card className="p-5 sm:p-6"><h2 className="font-semibold">訂單進度</h2><div className="mt-6">{order.timeline.map((item, index) => <div key={item.label} className="relative flex min-h-16 gap-4 last:min-h-0"><div className={`relative z-10 grid h-7 w-7 shrink-0 place-items-center rounded-full border ${item.completed ? 'border-[#5f725d] bg-[#5f725d] text-white' : 'border-stone-200 bg-white text-stone-300'}`}>{item.completed ? <Check size={14}/> : <span className="h-1.5 w-1.5 rounded-full bg-current"/>}</div>{index < order.timeline.length - 1 && <div className={`absolute left-[13px] top-7 h-[calc(100%-4px)] w-px ${item.completed ? 'bg-[#93a48f]' : 'bg-stone-200'}`}/>}<div className="pt-1"><p className={`text-sm font-medium ${item.completed ? 'text-stone-800' : 'text-stone-400'}`}>{item.label}</p>{item.time && <p className="mt-1 text-xs text-stone-400">{item.time}</p>}</div></div>)}</div></Card></div><OrderSummary order={order}/></div></div>; };

const Info = ({ icon, label, value }: { icon: React.ReactNode; label: string; value: string }) => <div className="flex gap-3"><div className="mt-0.5 text-stone-400 [&>svg]:h-5 [&>svg]:w-5">{icon}</div><div><dt className="text-xs text-stone-400">{label}</dt><dd className="mt-1 whitespace-pre-line text-sm leading-6 text-stone-700">{value}</dd></div></div>;
