import { useMemo, useState } from 'react';
import { CalendarDays, ClipboardX, Eye, RefreshCcw, XCircle } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import type { Order, OrderStatus } from '../../types';
import { useOrderStore } from '../../stores/useOrderStore';
import { useUIStore } from '../../stores/useUIStore';
import { formatCurrency, formatDate } from '../../utils/format';
import { OrderStatusBadge } from '../../components/orders/OrderComponents';
import { Button, Card, ConfirmDialog, DataTable, DateRangePicker, EmptyState, PageHeader, Pagination, SearchInput, type DataColumn } from '../../components/common/ui';

const tabs: Array<{ value: 'all' | OrderStatus; label: string }> = [{ value: 'all', label: '全部' }, { value: 'pending', label: '待確認' }, { value: 'processing', label: '處理中' }, { value: 'completed', label: '已完成' }, { value: 'cancelled', label: '已取消' }];
export const OrdersPage = () => {
  const orders = useOrderStore((state) => state.orders); const cancelOrder = useOrderStore((state) => state.cancelOrder); const reorder = useOrderStore((state) => state.reorder); const showToast = useUIStore((state) => state.showToast); const navigate = useNavigate();
  const [status, setStatus] = useState<'all' | OrderStatus>('all'); const [search, setSearch] = useState(''); const [start, setStart] = useState(''); const [end, setEnd] = useState(''); const [page, setPage] = useState(1); const [cancelId, setCancelId] = useState<string | null>(null); const pageSize = 5;
  const filtered = useMemo(() => orders.filter((order) => (status === 'all' || order.status === status) && (!search || order.id.toLowerCase().includes(search.toLowerCase())) && (!start || order.deliveryDate >= start) && (!end || order.deliveryDate <= end)), [orders, status, search, start, end]);
  const paged = filtered.slice((page - 1) * pageSize, page * pageSize); const totalPages = Math.max(1, Math.ceil(filtered.length / pageSize));
  const performReorder = (id: string) => { const result = reorder(id); if (result.added > 0) showToast(`已將 ${result.added} 項餐點加入購物車`); if (result.unavailable.length > 0) showToast(`${result.unavailable.join('、')} 目前無法訂購`, 'warning'); };
  const columns: Array<DataColumn<Order>> = [
    { key: 'id', title: '訂單編號', render: (order) => <div><p className="font-medium">#{order.id}</p><p className="mt-1 text-xs text-stone-400">{formatDate(order.orderedAt)}</p></div> },
    { key: 'delivery', title: '送餐時間', render: (order) => <div><p>{formatDate(order.deliveryDate)}</p><p className="mt-1 text-xs text-stone-400">{order.deliveryTime}</p></div> },
    { key: 'person', title: '訂購人', render: (order) => <div><p>{order.customerName}</p><p className="mt-1 text-xs text-stone-400">{order.department}</p></div> },
    { key: 'status', title: '狀態', render: (order) => <OrderStatusBadge status={order.status}/> },
    { key: 'total', title: '總金額', render: (order) => <span className="font-medium">{formatCurrency(order.total)}</span> },
    { key: 'actions', title: '操作', render: (order) => <div className="flex items-center gap-1"><Button variant="ghost" size="icon" title="查看詳情" onClick={() => navigate(`/orders/${order.id}`)}><Eye size={16}/></Button>{order.status === 'pending' && <Button variant="ghost" size="icon" title="取消訂單" onClick={() => setCancelId(order.id)}><XCircle size={16}/></Button>}<Button variant="ghost" size="icon" title="再訂一次" onClick={() => performReorder(order.id)}><RefreshCcw size={15}/></Button></div> },
  ];
  return <div className="space-y-5"><PageHeader eyebrow="MY ORDERS" title="我的訂單" description="查詢配送進度、取消待確認訂單，或快速再訂一次。"/><Card className="p-4"><div className="grid gap-3 lg:grid-cols-[1fr_1.3fr]"><SearchInput value={search} onChange={(value) => { setSearch(value); setPage(1); }} placeholder="搜尋訂單編號…"/><DateRangePicker start={start} end={end} onStartChange={(value) => { setStart(value); setPage(1); }} onEndChange={(value) => { setEnd(value); setPage(1); }}/></div><div className="mt-4 flex gap-2 overflow-x-auto border-t border-stone-100 pt-4">{tabs.map((tab) => <button key={tab.value} onClick={() => { setStatus(tab.value); setPage(1); }} className={`min-h-9 shrink-0 rounded-lg px-4 text-xs font-medium ${status === tab.value ? 'bg-[#403a2c] text-white' : 'bg-stone-100 text-stone-600 hover:bg-stone-200'}`}>{tab.label}</button>)}</div></Card>{paged.length === 0 ? <Card><EmptyState icon={<ClipboardX size={36}/>} title="目前沒有符合的訂單" description="調整日期、狀態或訂單編號後再試一次。"/></Card> : <><Card className="hidden overflow-hidden md:block"><DataTable data={paged} columns={columns} getKey={(order) => order.id}/></Card><div className="space-y-3 md:hidden">{paged.map((order) => <Card key={order.id} className="p-4"><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-semibold">#{order.id}</p><p className="mt-1 flex items-center gap-1 text-xs text-stone-400"><CalendarDays size={13}/>{formatDate(order.deliveryDate)} {order.deliveryTime}</p></div><OrderStatusBadge status={order.status}/></div><div className="mt-4 flex items-end justify-between border-t border-stone-100 pt-3"><div><p className="text-xs text-stone-400">{order.customerName} · {order.department}</p><p className="mt-1 font-semibold">{formatCurrency(order.total)}</p></div><div className="flex gap-1"><Button variant="secondary" size="sm" onClick={() => navigate(`/orders/${order.id}`)}>詳情</Button><Button variant="ghost" size="icon" onClick={() => performReorder(order.id)}><RefreshCcw size={15}/></Button></div></div></Card>)}</div><Pagination page={Math.min(page, totalPages)} totalPages={totalPages} onChange={setPage}/></>}<ConfirmDialog open={cancelId !== null} onClose={() => setCancelId(null)} onConfirm={() => { if (cancelId && cancelOrder(cancelId)) showToast('訂單已取消'); else showToast('此訂單目前無法取消', 'error'); }} title="取消這筆訂單？" description="取消後無法復原；只有待確認的訂單能在截止時間前取消。" confirmLabel="確認取消"/></div>;
};
